name: Build, Test, and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies with pnpm
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm run build

    - name: Test
      run: pnpm run test

    - name: Set up .npmrc file for auth
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Publish to npm
      if: github.ref == 'refs/heads/main' # Only publish if on the main branch
      run: pnpm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create GitHub Release with dist/
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload dist/ to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mirrormorph.js
        asset_name: mirrormorph.js
        asset_content_type: application/javascript
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
